version: '2'

services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile
    image: elasticsearch-aknn:6.3.2
    environment:
      ## Specifies the Java heap size used
      ## Read
      ##  https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
      ## for more info
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - index:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    environment:
      SERVER_NAME: kibana.test
      ELASTICSEARCH_HOSTS: "http://myelasticsearch:9200"
      ELASTICSEARCH_URL: "http://myelasticsearch:9200"
    ports:
      - 5601:5601
    links:
      - "elasticsearch:myelasticsearch"

volumes:
  index: # Scratch space for ElasticSearch index, will be rebuilt if lost
